# Generated by Django 5.2.4 on 2025-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=10000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
