# Generated by Django 5.2.4 on 2025-07-15 17:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['start_date'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekty'},
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_number',
            field=models.CharField(default='', max_length=100, verbose_name='Numer umowy o finansowanie'),
        ),
        migrations.AddField(
            model_name='project',
            name='agreement_sign_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Data podpisania umowy'),
        ),
        migrations.AddField(
            model_name='project',
            name='call_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nazwa i edycja konkursu'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email kontaktowy'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.CharField(default='', max_length=150, verbose_name='Osoba do kontaktu'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon kontaktowy'),
        ),
        migrations.AddField(
            model_name='project',
            name='domestic_partners',
            field=models.TextField(blank=True, default='', verbose_name='Partnerzy krajowi'),
        ),
        migrations.AddField(
            model_name='project',
            name='executing_unit',
            field=models.CharField(default='', max_length=200, verbose_name='Jednostka realizująca'),
        ),
        migrations.AddField(
            model_name='project',
            name='foreign_partners',
            field=models.TextField(blank=True, default='', verbose_name='Partnerzy zagraniczni'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_agency',
            field=models.CharField(default='', max_length=200, verbose_name='Instytucja finansująca'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_decision_date',
            field=models.DateField(default=None, verbose_name='Data decyzji o finansowaniu'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_number',
            field=models.CharField(default='', max_length=100, verbose_name='Nr projektu w instytucji finansującej'),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nr wewnętrzny projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Kierownika projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon Kierownika projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='principal_investigator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.CharField(default='', max_length=200, verbose_name='Lider projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_support',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='supported_projects', to=settings.AUTH_USER_MODEL, verbose_name='Osoba wspierająca'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('solo', 'Projekt indywidualny'), ('consortium', 'Projekt w ramach grupy podmiotów')], default='', max_length=20, verbose_name='Typ projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budżet całkowity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Opis projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='Data zakończenia projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=None, verbose_name='Data rozpoczęcia projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
