# Generated by Django 5.2.4 on 2025-07-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_options_project_agreement_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='domestic_partners',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Partnerzy krajowi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='foreign_partners',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Partnerzy zagraniczni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_support',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='supported_projects', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun Projektu'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PI', 'Kierownik projektu'), ('PS', 'Opiekun projektu'), ('CO', 'Współpracownik'), ('AD', 'Administrator')], max_length=2)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przypisania')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny członek zespołu')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Notatka (np. zakres obowiązków)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project', verbose_name='Projekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Członek zespołu',
                'verbose_name_plural': 'Członkowie zespołu',
                'ordering': ['project', 'role', 'user'],
                'unique_together': {('project', 'role', 'user')},
            },
        ),
    ]
