# Generated by Django 5.2.4 on 2025-07-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_domestic_partners_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
