# Generated by Django 5.2.4 on 2025-08-01 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_expenses_projectchangelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectchangelog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectchangelog',
            name='status',
            field=models.CharField(choices=[('draft', 'W przygotowaniu'), ('pending', 'W rozpatrywaniu'), ('approved', 'Zatwierdzony')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='projectchangelog',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='agreement_sign_date',
            field=models.DateField(default=None, verbose_name='Data podpisania umowy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Opis projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('IND', 'Projekt indywidualny'), ('GR', 'Projekt wielopodmiotowy')], default='', max_length=20, verbose_name='Typ projektu'),
        ),
        migrations.AlterField(
            model_name='projectchangelog',
            name='description',
            field=models.TextField(),
        ),
    ]
