# Generated by Django 5.2.4 on 2025-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_timestamp_projectchangelog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'W przygotowaniu'), ('in_progress', 'W trakcie'), ('done', 'Zatwierdzone')], default='pending', max_length=20),
        ),
    ]
