# Generated by Django 5.2.4 on 2025-08-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='progress',
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('planned', 'Zaplanowany'), ('in_progress', 'W trakcie'), ('completed', 'Zakończony'), ('delayed', 'Opóźniony')], default='pending', max_length=20),
        ),
    ]
