# Generated by Django 5.2.4 on 2025-08-13 20:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subtask_options_remove_milestone_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['project', 'role', 'user', 'assigned_at'], 'verbose_name': 'Członek zespołu', 'verbose_name_plural': 'Członkowie zespołu'},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='completed',
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('equipment', 'Aparatura i sprzęt'), ('salary', 'Wynagrodzenie'), ('travel', 'Podróże służbowe'), ('services', 'Usługi obce'), ('other', 'Inne')], default='', max_length=20, verbose_name='Kategoria wydatków'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=core.models.receipt_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='responsible',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='agreement_number',
            field=models.CharField(max_length=100, verbose_name='Numer umowy o finansowanie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='agreement_sign_date',
            field=models.DateField(verbose_name='Data podpisania umowy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='call_name',
            field=models.CharField(max_length=150, verbose_name='Nazwa i edycja konkursu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email kontaktowy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Osoba do kontaktu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, null=True, verbose_name='Telefon kontaktowy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Opis projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domestic_partners',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Partnerzy krajowi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Data zakończenia projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='executing_unit',
            field=models.CharField(max_length=200, verbose_name='Jednostka realizująca'),
        ),
        migrations.AlterField(
            model_name='project',
            name='foreign_partners',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Partnerzy zagraniczni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.CharField(max_length=200, verbose_name='Instytucja finansująca'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_decision_date',
            field=models.DateField(verbose_name='Data decyzji o finansowaniu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_number',
            field=models.CharField(max_length=100, verbose_name='Nr projektu w instytucji finansującej'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nr wewnętrzny projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Projekt aktywny?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_email',
            field=models.EmailField(max_length=254, verbose_name='Email Kierownika projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_phone',
            field=models.CharField(max_length=20, verbose_name='Telefon Kierownika projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lider projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supported_projects', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun Projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('IND', 'Projekt indywidualny'), ('GR', 'Projekt wielopodmiotowy')], max_length=20, verbose_name='Typ projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Data rozpoczęcia projektu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projectchangelog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='core.project'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('planned', 'Zaplanowany'), ('in_progress', 'W trakcie'), ('completed', 'Zakończony'), ('delayed', 'Opóźniony')], default='planned', max_length=20),
        ),
    ]
